<?php

function myngl_user_init() {
  global $user;

  if (($user->uid == 0) && (arg(0) != 'user') && (!(arg(0) == 'myngl' && arg(2) == 'rsvp')) && (!(arg(0) == 'myngl' && arg(2) == 'confirmed'))) {
    if (!drupal_is_cli()) { //add to fix Drush bug
      if (arg(0) != 'fboauth') {
        drupal_goto('user');
      }
    }
  }

  // Block users if not brand rep or administrator
  if (drupal_match_path(current_path(),"node/*/edit")){
    if (in_array("administrator", $user->roles)){
    }
    elseif(in_array("brand rep", $user->roles) ){
      $myngl = node_load(arg(1));
      $brand_reps = $myngl->field_brand_rep2['und'];
      $brand_reps_uids = array();
      foreach($brand_reps as $row){
        $brand_reps_uids[] = $row['uid'];
      }
      if (!in_array($user->uid, $brand_reps_uids)){
        drupal_goto('user');
      }
    }
    else{
      drupal_goto('user');
    }
  }
}

function myngl_user_user_login(&$edit, $account) {
  if (isset($_COOKIE['Drupal_visitor_rsvp'])) {
    $myngl_nid = htmlspecialchars($_COOKIE['Drupal_visitor_rsvp']);
  }

  if (isset($myngl_nid)) {
    $email = $account->mail;
    $myngl_node = node_load($myngl_nid);

    foreach ($myngl_node->field_myngl_invitees['und'] as $i) {
      $u = array_shift(entity_load('field_collection_item', array($i['value'])));

      if ($u->field_invitee_email_address['und'][0]['safe_value'] == $email) {
        $u->field_invitee_status['und'][0]['value'] = 'RSVP';

        if (isset($_COOKIE['Drupal_visitor_rsvp_date'])) {
          $u->field_invitee_rsvp_date['und'][0]['value'] = $_COOKIE['Drupal_visitor_rsvp_date'];
        } else {
          $u->field_invitee_rsvp_date['und'][0]['value'] = $myngl_node->field_myngl_dates['und'][0]['value'];
        }
        $u->field_invitee_user_account['und'][0]['uid'] = $account->uid;
        $u->save(TRUE);

        user_cookie_delete('rsvp');

        drupal_goto("myngl/$myngl_nid/confirmed");
      }
    }
  }

  global $user;
  if (in_array('administrator', $user->roles)) {
    drupal_goto('admin');
  }
}

function myngl_user_register_validate($element, &$form_state, $form){
  //print "<pre>";
  //print_r($element);

  //die;
  if ($element['und']['#value']==0) {

     form_error($element, t('Must agree to Terms and Conditions.'));
   }

}

function myngl_user_form_alter(&$form, &$form_state, $form_id) {



  switch($form_id) {

    case 'user_login' :
      if (isset($_COOKIE['Drupal_visitor_rsvp'])) {
        $myngl_nid = htmlspecialchars($_COOKIE['Drupal_visitor_rsvp']);

        if (isset($myngl_nid)) {

          $form['cutomtext'] = array(
            '#type' => 'item',
            '#markup' => '<div style="width:400px; height:50px;font-style:italic;margin-bottom:30px;" >To RSVP for this invite-only event and be invited to other exclusive events, please create your account for theMyngl.</div>',
            '#weight' => -19, // Adjust so that you can place it whereever
          );
        }

      }

      if (!isset($form['cutomtext'])){


        $form['cutomtext'] = array(
          '#type' => 'item',
          '#markup' => '<div style="width:400px; height:50px;margin-bottom:30px;" ></div>',
          '#weight' => -19, // Adjust so that you can place it whereever
        );

      }
      $form['name']['#description'] = '';

      $form['pass']['#description'] = '';

      $form['facebook_signin'] = array (
        '#markup' => '<div id="registration-facebook">
                        <p class="form-button-text">Facebook user?<br><br>Sign in with<br><span>FACEBOOK CONNECT</span></p>
                        <a  class="facebook-action-connect" rel="nofollow" href="https://www.facebook.com/dialog/oauth?client_id=352510628237304&redirect_uri=http%3A//www.themyngl.com/fboauth/connect&scope=email%2Cread_friendlists">
                        <span class="fa-stack fa-lg" id="facebook-signin"> <i class="fa fa-circle fa-stack-2x"></i> <i class="fa fa-facebook fa-stack-1x fa-inverse"></i> </span>
                        </a>
                      </div>',
        '#weight' => -20
      );
      $form['create_account'] = array (
        '#markup' => '<a href="/user/register" id="create-account" class="form-button"> NEW ACCOUNT</a>',
        '#weight' => 900
      );
      $form['forgot_password'] = array (
        '#markup' => '<a href="/user/password" id="forgot-password">Forgot Password?</a>',
        '#weight' => 1000
      );
      break;

    case 'user_pass' :
      $form['message'] = array (
      '#markup' => '<p>Forgot your password for theMyngl?  No problem. <br /><br />Enter your Email address and we’ll send it to you.  </p><br />',
        '#weight' => 0,
      );
      $form['cancel'] = array (
        '#markup' => '<a href="/user" id="forgot-password-cancel">Cancel</a>',
        '#weight' => 200
      );
      break;

    case 'user_register_form' :
      $form['actions']['submit']['#value'] = 'REGISTER';
      //$form['#validate'][] = 'myngl_user_register_validate';


      if (isset($_COOKIE['Drupal_visitor_rsvp'])) {
        $cookie['rsvp_through_registration'] = $_COOKIE['Drupal_visitor_rsvp'];
        user_cookie_save($cookie);
        //$myngl_nid = htmlspecialchars($_COOKIE['Drupal_visitor_rsvp']);

        if (isset($myngl_nid)) {

          $form['cutomtext'] = array(
            '#type' => 'item',
            '#markup' => '<div style="width:400px;height:50px;font-style:italic;margin-bottom:30px;" >To RSVP for this invite-only event and be invited to other exclusive events, please create your account for theMyngl.</div>',
            '#weight' => -19, // Adjust so that you can place it whereever
          );
        }

      }

      if (!isset($form['cutomtext'])){

          $form['cutomtext'] = array(
            '#type' => 'item',
            '#markup' => '<div class = "testee" style="width:400px;height:50px;margin-bottom:30px;" ></div>',
            '#weight' => -19, // Adjust so that you can place it whereever
          );

      }
      $form['field_terms_and_condition']['und']['#title']='I have read and agree to the <a href="#" id="terms-overlay-link">Terms & Conditions</a>.';
      $form['field_terms_and_condition']['#element_validate'] = array('myngl_user_register_validate');


      $form['facebook_signin'] = array (
        '#markup' => '<div id="registration-facebook">
                        <p class="form-button-text">Facebook user?<br><br>Sign in with<br><span>FACEBOOK CONNECT</span></p>
                        <a  class="facebook-action-connect" rel="nofollow" href="https://www.facebook.com/dialog/oauth?client_id=352510628237304&redirect_uri=http%3A//www.themyngl.com/fboauth/connect&scope=email%2Cread_friendlists">
                        <span class="fa-stack fa-lg" id="facebook-signin"> <i class="fa fa-circle fa-stack-2x"></i> <i class="fa fa-facebook fa-stack-1x fa-inverse"></i> </span>
                        </a>
                      </div>',
        '#weight' => -20
      );

      $form['create_account'] = array (
        '#markup' => '<div class="form-button-wrapper">
                        <p class="form-button-text">Already have an account?</p>
                        <a href="/user" id="regiser-cancel" class="form-button">LOGIN HERE</a>
                      </div>',

        '#weight' => 900
      );
      break;

    case 'user_profile_form' :

      global $user;
      $form['actions']['submit']['#value'] = 'SUBMIT CHANGES';


      $name = $form['#user']->field_first_name['und'][0]['safe_value'] . ' ' .
              $form['#user']->field_last_name['und'][0]['safe_value'] ;


      $form['account']['pass']['#process'] = array('form_process_password_confirm', 'myngl_user_password_confirm');

      $form['name'] = array(
            '#type' => 'item',
            '#markup' => 'ACCOUNT:<span id="account" style="font-weight:bold;">'. $form['#user']->name . '</span><br/><br/>NAME: <span id="name">' . $name . '</span>',
            '#weight' => -19, // Adjust so that you can place it whereever
          );
      $form['account']['mail']['#weight'] = -6;
      $form['cancel'] = array (
        '#markup' => '<a href="/user" id="edit-profile-cancel">Cancel edits</a>',
        '#weight' => 200
      );

      $form['field_terms_and_condition']['#access'] = FALSE;

      if (isset($_GET['pass-reset-token'])) {
        $form['#submit'][] = 'myngl_user_redirect';
      }
      

      $form['#after_build'][] = 'myngl_user_timezone_modify';
      break;


  }
}

function myngl_user_timezone_modify($form, &$form_state) {
  //file_put_contents('test123.txt', print_r($form['timezone']['timezone'], "TRUE"));
  $old_options = $form['timezone']['timezone']['#options'];
  $new_options=array();

  $new_options[''] = $old_options[''];
  $new_options['America/Anchorage'] = $old_options['America/Anchorage'];
  $new_options['America/Chicago'] = $old_options['America/Chicago'];
  $new_options['America/Denver'] = $old_options['America/Denver'];
  $new_options['America/Detroit'] = $old_options['America/Detroit'];
  $new_options['America/Detroit'] = $old_options['America/Detroit'];
  $new_options['America/Indiana/Indianapolis'] = $old_options['America/Indiana/Indianapolis'];
  $new_options['America/Kentucky/Louisville'] = $old_options['America/Kentucky/Louisville'];
  $new_options['America/Los_Angeles'] = $old_options['America/Los_Angeles'];
  $new_options['America/New_York'] = $old_options['America/New_York'];
  $new_options['America/Phoenix'] = $old_options['America/Phoenix'];
  $new_options['America/Toronto'] = $old_options['America/Toronto'];
  $new_options['America/Vancouver'] = $old_options['America/Vancouver'];
  $new_options['UTC'] = $old_options['UTC'];




  $form['timezone']['timezone']['#options'] = $new_options;
  return $form;
}

function myngl_user_redirect() {
  drupal_goto('user');
}

/**
 * Implementation of expand_password_confirm.
 */
function myngl_user_password_confirm($element) {
  $element['pass1']['#title'] = t("New Password");
  $element['pass2']['#title'] = t("Confirm New Password");
  return $element;
}


function myngl_user_form_profile2_form_alter(&$form, &$form_state) {
  if ($uid = $form['#user']->uid) {
    $user = user_load($uid);
    $u = entity_metadata_wrapper('user', user_load($uid));
    $profile = profile2_load_by_user($uid, 'profile');

    if ($profile) {
      $p = entity_metadata_wrapper('profile2', $profile);
    }
  }

  $form['profile_profile']['field_interests']['und']['#title'] = 'To personalize your Myngl experience, tell us your interests:<br/> (check all that are appropriate)';
  $form['profile_profile']['field_picture']['und'][0]['#title'] = '';
  $form['profile_profile']['field_city']['und'][0]['#prefix'] = ' <span class="profile-name">NAME: <strong>'.$u->field_first_name->value().' '.$u->field_last_name->value().'</strong></span><br />';

  $form['profile_profile']['field_date_of_birth']['und'][0]['#suffix'] =
    '<div class ="profile-flipswitch" id="profile-gender" >
      <div id="label" style="float:left;">Gender</div>
      <div class="option-left" style="position:absolute; left:100px;">Male</div>
      <div id="gender-switch" class="switch" >
        <div id="gender-switch-inner" class="switch-inner">
          <div id = "gender-switch-knob" class="switch-knob" ></div>
        </div>
      </div>
      <div class="option-right" style="position:absolute; left:250px;">Female</div>
    </div>
    <!--
    <div id="status" class ="profile-flipswitch">
      <div id="label" style="float:left;">Status</div>
      <div class="option-left" style="position:absolute; left:100px;">Single</div>
      <div id="status-switch" class="switch">
        <div id="status-switch-inner" class="switch-inner" >
          <div id = "status-switch-knob" class="switch-knob"></div>
        </div>
      </div>
      <div class="option-right" style="position:absolute; left:250px;">In Relationship</div>
    </div>-->';

  if (isset($p)) {
    $pic = $p->field_picture->value();
  }
  //print_r($form); exit();

  if (!isset($pic['uri'])) {
    if (isset($user->picture)) {
      $form['profile_profile']['field_picture']['und']['#prefix'] =
        " <div id='default-image-wrapper'>" .
          theme_image_style(array('style_name' => 'user_profile_circle_image', 'path' => $user->picture->uri, 'attributes' => array('class' => 'default-profile-pic'), 'height' => null, 'width' => null)) .
        " <br /><a href='#!' class='link-small' onclick='jQuery(\"#default-image-wrapper\").hide();jQuery(\".image-widget\").show();'>Upload a profile picture</a>
          <script>jQuery(document).ready(function () { jQuery('.image-widget').hide(); });</script>
          </div>";
    } else {
      $form['profile_profile']['field_picture']['und']['#prefix'] =
        " <div id='default-image-wrapper'>" .
          theme_image_style(array('style_name' => 'user_profile_circle_image', 'path' => 'public://default-user-profile.png', 'attributes' => array('class' => 'default-profile-pic'), 'height' => null, 'width' => null)) .
        " <br /><a href='#!' class='link-small' onclick='jQuery(\"#default-image-wrapper\").hide();jQuery(\".image-widget\").show();'>Upload a profile picture</a>
          <script>jQuery(document).ready(function () { jQuery('.image-widget').hide(); });</script>
          </div>";
    }
  }

}

function myngl_user_user_view_alter(&$build){
  if (isset($_COOKIE['Drupal_visitor_rsvp_through_registration'])){
    myngl_myngl_complete($_COOKIE['Drupal_visitor_rsvp_through_registration']);
  }
}

function myngl_user_fboauth_actions() {
  // Give each action a unique key, such as "mymodule_photo_import" for a photo
  // import. This function should begin with the name of your module.
  $actions['mymodule_photo_import'] = array(
    // Give you action a human-readable name. This will be used when showing
    // the user a link to start this action.
    'title' => t('Import my Facebook photos'),
   

// Specify the name of your callback function that contains the import.
    'callback' => 'mymodule_fboauth_action_photo_import',
   

// Specify permissions you need to do this action. See the Facebook API for
    // a list: http://developers.facebook.com/docs/authentication/permissions/
    'permissions' => array(
      'user_photos', // Gets access to a user's photos.
    ),
   

// Optionally specify a file that contains your callback function. If you
    // put your callback function in the .module file, this is unnecessary.
    // 'file' => 'mymodule.inc',
    // Optionally define a theme function for printing out your link (not
    // including the "theme_" prefix). If you use this option, you must register
    // this function in hook_theme(). If you don't use this option, the link
    // will be output with the theme_fboauth_action() function or the automatic
    // suggestion theme_fboauth_action__[action_name]().
    // 'theme' => 'mymodule_fboauth_action',
 

);
  return $actions;
}

function myngl_user_fboauth_action_photo_import($app_id, $access_token) {
  // Query against the Facebook Graph API. See the Facebook API for a list of
  // commands: http://developers.facebook.com/docs/reference/api/
  $result = fboauth_graph_query('me/photos', $access_token);

print '<pre>';

  foreach ($result->data as $photo) {
    print_r($photo);
  }

exit;
 

// Optionally set a completion or error message.
  drupal_set_message(t('Import complete!'));
 

// Optionally return a path to which the user will be redirected. If not set
  // the path in the $_REQUEST['destination'] variable will be used. If there
  // is no path at all specified, the user will be redirected to the homepage.
  return 'mymodule/import-complete';
}

 
