<?php

function myngl_page_title_init() {
  $path = current_path();

  // change titles based on path
  switch (TRUE) {
    case ($path == 'user') :
      drupal_set_title('ACCOUNT LOGIN');
      break;

    case ($path == 'user/password') :
      drupal_set_title('FORGOT YOUR PASSWORD?');
      break;
    
    case ($path == 'user/register') :
      drupal_set_title('CREATE YOUR MYNGL ACCOUNT');
      break;

    case preg_match('|user/\d*$|', $path) :
      $user = user_load(arg(1));
      $u = entity_metadata_wrapper('user', $user);

      drupal_set_title(strtoupper($u->field_first_name->value())."'s DASHBOARD");
      break;

    case preg_match('|user/\d*/edit/profile$|', $path) :
      drupal_set_title('COMPLETE YOUR PROFILE');
      break;
    
    case preg_match('|user/\d*/edit$|', $path) :
      drupal_set_title('EDIT YOUR SETTINGS');
      break;


  }

}
