<?php

function myngl_page_title_init() {
  $path = current_path();

  // change titles based on path
  switch (TRUE) {
    case ($path == 'user' || $path == "") :
      global $user;
      if ($user->uid != 0){
        $u = entity_metadata_wrapper('user', $user);
        drupal_set_title(strtoupper($u->field_first_name->value())."'s DASHBOARD");
      }
      else {
        if (isset($_COOKIE['Drupal_visitor_rsvp'])) {
          $myngl_nid = htmlspecialchars($_COOKIE['Drupal_visitor_rsvp']);
        }

        if (isset($myngl_nid)) {
          drupal_set_title('LOGIN TO COMPLETE RSVP');
        } else {
          drupal_set_title('ACCOUNT LOGIN');

        }
      }

      break;

    case ($path == 'user/password') :
      drupal_set_title('FORGOT YOUR PASSWORD?');
      break;
    
    case ($path == 'user/register') :
      if (isset($_COOKIE['Drupal_visitor_rsvp'])) {
        $myngl_nid = htmlspecialchars($_COOKIE['Drupal_visitor_rsvp']); 
      }

      if (isset($myngl_nid)) {
        drupal_set_title('CREATE YOUR ACCOUNT FOR theMYNGL');
      } else {
        drupal_set_title('CREATE YOUR ACCOUNT FOR theMYNGL');
      }

      break;

    case preg_match('|user/\d*$|', $path) :

      $user = user_load(arg(1));
      $u = entity_metadata_wrapper('user', $user);
      drupal_set_title(strtoupper($u->field_first_name->value())."'s DASHBOARD");

      break;

    case preg_match('|user/\d*/edit/profile$|', $path) :
      drupal_set_title('COMPLETE YOUR PROFILE');
      break;
    
    case preg_match('|user/\d*/edit$|', $path) :
      drupal_set_title('EDIT YOUR SETTINGS');
      break;


  }

}
