<?php

function myngl_rewards_menu() {
  $items['user/%user/rewards'] = array(
    'title' => 'REWARDS',
    'page callback' => 'myngl_rewards_page',
    'page arguments' => array(2),
    'access callback' => TRUE, 
  );

  return $items;
}

function myngl_rewards_theme() {
  $items['myngl_rewards'] =  array(
                          'template' => 'myngl-rewards',
                          'variables' => array('points' => null),
                        );
  return $items;
}

function myngl_rewards_page() {
  $rewards = rand(100,1000);

  $output = theme('myngl_rewards', array('points' => $rewards));

  return $output;
}
