<?php

function myngl_activities_menu() {
  $items['user/%user/activities'] = array(
    'title' => 'ACTIVITY',
    'page callback' => 'myngl_activities_page',
    'page arguments' => array(2),
    'access callback' => TRUE,
  );

  return $items;
}

function myngl_activities_theme() {
  $items['myngl_activities'] =  array(
                          'template' => 'myngl-activities',
                          'variables' => array('activities' => null),
                        );
  return $items;
}

function myngl_activities_page() {
  $description_mapping = array(

      'visiting_lobby' => "Visit lobby",
      'visiting_social' => "Visit lounge",
      'opening_ugc_win' => "View UGC window",
      'opening_pov_win' => "View POV window",
      'visiting_theate' => "Visit theater",
      'visiting_activi' => "Visit playroom",
      'playroom_activi' => "Play game",
      'sending_ct_msg' => "Send chat message",


  );
  global $user;

  $activities = array();

  $result = db_query("  SELECT * FROM {myngl_rewards_history} 
                        WHERE user_id = :uid 
                        GROUP BY description 
                        ORDER BY timestamp DESC ", array(':uid' => $user->uid));

  foreach ($result as $r) {

    if (date('Ymd') == date('Ymd', $r->timestamp)) {
      $day = 'Today';
    } elseif (date('Ymd', time() - 86400) == date('Ymd', $r->timestamp)) {
      $day = 'Yesterday';
    } else {
      $day = floor((time() - $r->timestamp) / 86400).' DAYS AGO';
    }

    $activities[] = array(
      'date' => $r->timestamp,
      'day' => $day,
      'description' => (isset($description_mapping[$r->description]))?$description_mapping[$r->description]:$r->description,
      'points' => $r->points,
    );

  }

  $output = theme('myngl_activities', array('activities' => $activities));

  return $output;
}
